# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0010_auto_20171029_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left', to='login.Users'),
        ),
    ]
